//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Data
    {
        public int No { get; set; }
        [Required(ErrorMessage = "姓名不能為空!")]
        [StringLength(50)]
        [DisplayName("姓名")]
        public string Name { get; set; }
        [Required(ErrorMessage = "標題不能為空!")]
        [StringLength(50)]
        [DisplayName("標題")]
        public string Title { get; set; }
        [Required(ErrorMessage = "內容不能為空!")]
        [StringLength(50)]
        [DisplayName("內容")]
        public string Contents { get; set; }
    }
}
